services:
  toon:
    container_name: toon-tst
    image: toonguesser:testing
    entrypoint: ["./entrypoint.prd.sh"]
    environment:
      - NEXT_PUBLIC_MAX_DIFFICULTY=7
      - DATABASE_URL=${DATABASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - toon-net-tst
      - nginx-net

networks:
  toon-net-tst:
    name: toon-net-tst
  nginx-net:
    external: true