const cartoonConfig = {
  simpsons: {
    title: "The Simpsons",
    textStyles: {
      xxl: "text-5xl",
      xl: "text-3xl font-semibold",
      lg: "text-2xl",
      md: "text-xl",
      sm: "text-lg",
    },
    background: "bg-simpsons",
    backgroundImage: "bg-toon-simpsons",
    font: "font-simpsons",
    border: "border-simpsons",
    text: "text-simpsons",
    scroll: "scrollbar-simpsons",
    loading: "border-t-simpsons border-r-simpsons",
    pixelationLevels: [1, 11, 15, 19, 23, 27, 31, 35],
    saturationLevels: [0, 0.75, 0.8, 0.84, 0.88, 0.92, 0.96, 1],
    rotationAngles: [90, 180, 270],
  },
  pokemon: {
    title: "Pokémon",
    textStyles: {
      xxl: "text-6xl",
      xl: "text-3xl font-semibold",
      lg: "text-2xl",
      md: "text-xl",
      sm: "text-lg",
    },
    background: "bg-pokemon",
    backgroundImage: "bg-toon-pokemon",
    font: "font-pokemon",
    border: "border-pokemon",
    text: "text-pokemon",
    scroll: "scrollbar-pokemon",
    loading: "border-t-pokemon border-r-pokemon",
    pixelationLevels: [1, 11, 15, 19, 23, 27, 31, 35],
    saturationLevels: [0, 0.71, 0.75, 0.8, 0.84, 0.88, 0.92, 1],
    rotationAngles: [90, 180, 270],
  },
  dragonball: {
    title: "Dragon Ball",
    textStyles: {
      xxl: "text-5xl",
      xl: "text-2xl",
      lg: "text-xl",
      md: "text-lg",
      sm: "text-md",
    },
    background: "bg-dragonball",
    backgroundImage: "bg-toon-dragonball",
    font: "font-dragonball",
    border: "border-dragonball",
    text: "text-dragonball",
    scroll: "scrollbar-dragonball",
    loading: "border-t-dragonball border-r-dragonball",
    pixelationLevels: [1, 16, 20, 24, 28, 32, 36, 40],
    saturationLevels: [0, 0.71, 0.75, 0.8, 0.84, 0.88, 0.92, 1],
    rotationAngles: [180],
  },
};

export default cartoonConfig;
