services:
  cron:
    container_name: toon-cron-tst
    image: toonguesser-cron:testing
    entrypoint: ["./entrypoint.prd.sh"]
    environment:
      - PORT=8082
      - DATABASE_URL=${DATABASE_URL}
      - API_URL=http://toon-tst:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - toon-net-tst
      - nginx-net

networks:
  toon-net-tst:
    external: true
  nginx-net:
    external: true
